openstudio_path: ./openstudioapplication-1.6.0/
EPlus_file: ./openstudioapplication-1.6.0/EnergyPlus
osm_name_box: ./building_model/ITRC_2nd_6zone_OPEN_3.60.osm
weather_data: ./weather_data/USA_SC_Greenville-Spartanburg.Intl.AP.723120_TMY3.epw
iddfile: Energy+.idd
save_idf: run.idf
weight_file: ./weights/last.pth
replay_buffer: replay_buffer.pkl
HVAC_output: true
reset_dataframe: false
Train: true
signal_loss: false
AirWall_Switch: 'on'
Roof_Switch: 'off'
timestep_per_hour: 12
begin_month: 1
begin_day_of_month: 1
end_month: 12
end_day_of_month: 31
state_dim: 14
action_dim: 64
epochs: 10
lr: 0.001
gamma: 0.9
epsilon: 0
target_update: 10
buffer_size: 1000
minimal_size: 200
batch_size: 128
FPS: 1000
positive_reward: 0
signal_factor: 0
T_factor_day: 1
E_factor_day: 1.0e-05
T_factor_night: 0.1
E_factor_night: 1.0e-05
F_bottom: 60
F_top: 90
